name: Run All Project Checks
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write
  checks: write
  
jobs:
  run-checks:
    uses: plazacraft/poweretl-pipelines/.github/workflows/code-checks.yaml@main
    with:
      python-version: '3.13'
      projects: '["utils", "defs", "common", "databricks", "examples"]'
    secrets: inherit      
        
  run-tests:
    uses: plazacraft/poweretl-pipelines/.github/workflows/run-tests.yaml@main
    with:
      python-version: '3.13'
      projects: '["utils", "defs","common", "databricks","examples"]'
    secrets: inherit      