name: Trigger Publisher on Tag in Develop

on:
  push:
    tags:
      - '*-v*.*.*'
    # branches:
      # - develop

permissions:
  contents: write  # needed to upload release assets


jobs:
  call-publisher:
    uses: plazacraft/poweretl-pipelines/.github/workflows/publish-packages.yaml@test
    with:
      tag: ${{ github.ref_name }}
      ref: ${{ github.ref }}
      environment: tst