name: Publish To PyPI - PRD

on:
  push:
    tags:
      - '*-*.*.*-prd'

permissions:
  contents: write  # needed to upload release assets

jobs:
  call-publisher:
    uses: plazacraft/poweretl-pipelines/.github/workflows/publish-packages.yaml@main
    with:
      tag: ${{ github.ref_name }}
      ref: ${{ github.ref }}
      environment: prd
      python-version: '3.13'
    secrets: inherit   
