name: Publish To PyPI - TST

on:
  push:
    tags:
      - '*-*.*.*-tst'

permissions:
  contents: write  # needed to upload release assets

jobs:
  publish:
    name: Publish to PyPI Test
    runs-on: ubuntu-latest
    environment: tst
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish ${{ github.ref_name }} to PyPI
        uses: plazacraft/poweretl-pipelines/actions/publish-packages@feature/pylint
        with:
          tag: ${{ github.ref_name }}
          python-version: '3.13'
          poetry-pypi-url: ${{ vars.POETRY_PYPI_URL }}
          poetry-pypi-token: ${{ secrets.POETRY_PYPI_TOKEN }}      